name: CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - run: python -m pip install --upgrade pip
      - run: pip install -r requirements.txt
      - name: Lint import
        run: python - <<'PY'
import sys, importlib
mods = ["flask","openai","flask_cors","redis","flask_limiter","jwt","requests"]
for m in mods:
    try: importlib.import_module(m.replace("-","_"))
    except Exception as e:
        print("FAILED:", m, e); sys.exit(1)
print("OK")
PY
